/**
 * RefundGuard database seed script.
 *
 * 1. Connects to MongoDB using MONGO_URI (dotenv, backend/.env)
 * 2. Clears the relevant collections
 * 3. Loads the JSON generated by `npm run data:generate` from data/raw/
 * 4. Inserts the records
 * 5. Prints a concise summary
 *
 * Exits non-zero if MongoDB is unavailable so the failure is clearly reported,
 * without affecting normal (nonfatal) server startup behavior.
 */

require('dotenv').config();
const path = require('path');
const mongoose = require('mongoose');

const {
  Customer,
  Device,
  Transaction,
  Refund,
  Complaint,
} = require('./models');

const RAW_DIR = path.join(__dirname, '..', 'data', 'raw');

function loadJson(name) {
  return require(path.join(RAW_DIR, `${name}.json`));
}

async function seed() {
  const mongoUri = process.env.MONGO_URI;
  if (!mongoUri) {
    console.error(
      'MONGO_URI is not defined. Create backend/.env (see backend/.env.example) and set MONGO_URI. Seeding aborted.'
    );
    process.exit(1);
  }

  console.log('Connecting to MongoDB...');
  await mongoose.connect(mongoUri, { serverSelectionTimeoutMS: 8000 });
  console.log('Connected.\n');

  console.log('Clearing existing collections...');
  await Promise.all([
    Customer.deleteMany({}),
    Device.deleteMany({}),
    Transaction.deleteMany({}),
    Refund.deleteMany({}),
    Complaint.deleteMany({}),
  ]);

  const customers = loadJson('customers');
  const orders = loadJson('orders');
  const devices = loadJson('devices');
  const transactions = loadJson('transactions');
  const refunds = loadJson('refunds');
  const complaints = loadJson('complaints');

  await Customer.insertMany(customers);
  await Device.insertMany(devices);
  await Transaction.insertMany(transactions);
  await Refund.insertMany(refunds);
  await Complaint.insertMany(complaints);

  console.log('\n==============================================');
  console.log('RefundGuard database seeded successfully');
  console.log('==============================================');
  console.log(`Customers: ${customers.length}`);
  console.log(`Devices: ${devices.length}`);
  console.log(`Transactions: ${transactions.length}`);
  console.log(`Refunds: ${refunds.length}`);
  console.log(`Complaints: ${complaints.length}`);
  console.log(`(Orders metadata: ${orders.length})`);

  await mongoose.disconnect();
}

seed()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error('\nSeeding failed:', error.message);
    console.error(
      'Ensure MongoDB is running and MONGO_URI is correct in backend/.env'
    );
    process.exit(1);
  });